trigger:
  branches:
    include:
      - main  

stages:
  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - job: DeployYAMLs
        displayName: Apply YAML manifests
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: AzureCLI@2
            displayName: 'Login and apply manifests to AKS'
            inputs:
              azureSubscription: Aletheia-k8s
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Conectando ao cluster AKS..."
                az aks get-credentials --resource-group rg-cl-aletheia-dotnet --name aletheia-k8s --overwrite-existing

                echo "Executando script de deploy..."
                ./k8s/deploy.sh
