services:
  shared:
    build:
      context: .
      dockerfile: ./Shared/Dockerfile
    volumes:
      - shared_data:/app/shared

  api-gateway:
    build:
      context: .
      dockerfile: ./OcelotApiGateway/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
       - shared
       - claim-service
       - consultation-service
       - dentist-service
       - patient-service
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net

  claim-service:
    build:
      context: .
      dockerfile: ./ClaimService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net

  consultation-service:
    build:
      context: .
      dockerfile: ./ConsultationService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net

  dentist-service:
    build:
      context: .
      dockerfile: ./DentistService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net

  patient-service:
    build:
      context: .
      dockerfile: ./PatientService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net

networks:
    app_net:
      driver: bridge

volumes:
  shared_data:
    driver: local

