services:
  shared:
    build:
      context: .
      dockerfile: ./Shared/Dockerfile
    volumes:
      - shared_data:/app/shared

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80" # 5341 externa, 80 interna no container
    networks:
      - app_net
    volumes:
      - seq_data:/data

  api-gateway:
    build:
      context: .
      dockerfile: ./OcelotApiGateway/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
       - shared
       - claim-service
       - consultation-service
       - dentist-service
       - patient-service
       - auth-service 
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net

  auth-service:
    build:
      context: .
      dockerfile: ./AuthService/Dockerfile
    depends_on:
      - shared
      - dentist-service 
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net

  claim-service:
    build:
      context: .
      dockerfile: ./ClaimService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net
    env_file:
      - .env

  consultation-service:
    build:
      context: .
      dockerfile: ./ConsultationService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net
    env_file:
      - .env

  dentist-service:
    build:
      context: .
      dockerfile: ./DentistService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net
    env_file:
      - .env

  patient-service:
    build:
      context: .
      dockerfile: ./PatientService/Dockerfile
    depends_on:
      - shared
    volumes:
      - shared_data:/app/shared
    networks:
       - app_net
    env_file:
      - .env

networks:
  app_net:
    driver: bridge

volumes:
  shared_data:
    driver: local
  seq_data:
    driver: local
