# encoding: utf-8    

services:
  consultation-service:
    build:
      context: ./ConsultationService  
      dockerfile: Dockerfile 
    ports:
      - "5000:80"  
    networks:
      - app-network

  dentist-service:
    build:
      context: ./DentistService  
      dockerfile: Dockerfile 
    ports:
      - "5001:80" 
    networks:
      - app-network

  patient-service:
    build:
      context: ./PatientService 
      dockerfile: Dockerfile
    ports:
      - "5002:80"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  
