// <auto-generated />
using System;
using ConsultationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ConsultationService.Migrations
{
    [DbContext(typeof(FIAPDbContext))]
    partial class FIAPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsultationService.Models.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("consultation_date");

                    b.Property<double>("ConsultationValue")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("consultation_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("RiskStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("risk_status");

                    b.HasKey("Id");

                    b.ToTable("tb_consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
