apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claim-service
  template:
    metadata:
      labels:
        app: claim-service
    spec:
      containers:
        - name: claim-service
          image: aletheiadotnet.azurecr.io/acr-aletheia-dotnet/claim-service:latest
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: bd-configmap
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
