apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  loadBalancerIP: 191.234.178.113
  selector:
    app: api-gateway-service
  ports:
    - name: http
      protocol: TCP
      port: 80           
      targetPort: 8080   
