apiVersion: v1
kind: Service
metadata:
  name: seq
spec:
  selector:
    app: seq
  ports:
    - name: ui
      port: 80
      targetPort: 80
    - name: ingestion
      protocol: TCP
      port: 5341
      targetPort: 5341
